"""add_movie_model_and_update_relations

Revision ID: 633510998b1b
Revises: 20251111002325
Create Date: 2025-11-11 15:16:21.743875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '633510998b1b'
down_revision: Union[str, Sequence[str], None] = '20251111002325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_movie_vectors_updated'), table_name='movie_vectors')
    op.drop_table('movie_vectors')
    op.drop_index(op.f('idx_friendships_friend'), table_name='friendships')
    op.drop_index(op.f('idx_friendships_status'), table_name='friendships')
    op.drop_index(op.f('idx_friendships_user'), table_name='friendships')
    op.drop_constraint(op.f('uq_friendships_pair'), 'friendships', type_='unique')
    op.drop_index(op.f('idx_list_interactions_list'), table_name='list_interactions')
    op.drop_index(op.f('idx_list_interactions_type'), table_name='list_interactions')
    op.drop_index(op.f('idx_list_interactions_user'), table_name='list_interactions')
    op.drop_constraint(op.f('uq_list_interaction'), 'list_interactions', type_='unique')
    op.add_column('movies', sa.Column('tagline', sa.String(length=500), nullable=True))
    op.add_column('movies', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('production_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('movies', sa.Column('spoken_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('movies', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('movies', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('movies', 'original_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('movies', 'poster_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('movies', 'backdrop_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_movies_genres'), table_name='movies', postgresql_using='gin')
    op.drop_index(op.f('idx_movies_keywords'), table_name='movies', postgresql_using='gin')
    op.drop_index(op.f('idx_movies_language'), table_name='movies')
    op.drop_index(op.f('idx_movies_mood_tags'), table_name='movies', postgresql_using='gin')
    op.drop_index(op.f('idx_movies_release_date'), table_name='movies')
    op.drop_index(op.f('idx_movies_tone'), table_name='movies')
    op.drop_index(op.f('idx_movies_updated'), table_name='movies')
    op.drop_index(op.f('idx_movies_vote_average'), table_name='movies')
    op.drop_index(op.f('idx_movies_vote_count'), table_name='movies')
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.drop_column('movies', 'adult')
    op.drop_column('movies', 'keywords')
    op.drop_column('movies', 'mood_tags')
    op.drop_column('movies', 'tone')
    op.alter_column('profiles', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_profiles_last_active'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_privacy'), table_name='profiles')
    op.drop_index(op.f('idx_shared_lists_created'), table_name='shared_lists')
    op.drop_index(op.f('idx_shared_lists_owner'), table_name='shared_lists')
    op.drop_index(op.f('idx_shared_lists_public'), table_name='shared_lists')
    op.drop_index(op.f('idx_top10_category'), table_name='top10_list')
    op.drop_index(op.f('idx_top10_rank'), table_name='top10_list')
    op.drop_index(op.f('idx_top10_user'), table_name='top10_list')
    op.drop_constraint(op.f('uq_top10_user_category_rank'), 'top10_list', type_='unique')
    op.drop_index(op.f('idx_watchlist_added_at'), table_name='watchlist')
    op.drop_index(op.f('idx_watchlist_movie'), table_name='watchlist')
    op.drop_index(op.f('idx_watchlist_user'), table_name='watchlist')
    op.drop_constraint(op.f('uq_watchlist_user_movie'), 'watchlist', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_watchlist_user_movie'), 'watchlist', ['user_id', 'tmdb_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_watchlist_user'), 'watchlist', ['user_id'], unique=False)
    op.create_index(op.f('idx_watchlist_movie'), 'watchlist', ['tmdb_id'], unique=False)
    op.create_index(op.f('idx_watchlist_added_at'), 'watchlist', ['added_at'], unique=False)
    op.create_unique_constraint(op.f('uq_top10_user_category_rank'), 'top10_list', ['user_id', 'category', 'rank'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_top10_user'), 'top10_list', ['user_id'], unique=False)
    op.create_index(op.f('idx_top10_rank'), 'top10_list', ['rank'], unique=False)
    op.create_index(op.f('idx_top10_category'), 'top10_list', ['category'], unique=False)
    op.create_index(op.f('idx_shared_lists_public'), 'shared_lists', ['is_public'], unique=False)
    op.create_index(op.f('idx_shared_lists_owner'), 'shared_lists', ['owner_id'], unique=False)
    op.create_index(op.f('idx_shared_lists_created'), 'shared_lists', ['created_at'], unique=False)
    op.create_index(op.f('idx_profiles_privacy'), 'profiles', ['privacy_level'], unique=False)
    op.create_index(op.f('idx_profiles_last_active'), 'profiles', ['last_active'], unique=False)
    op.alter_column('profiles', 'bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('movies', sa.Column('tone', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('mood_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('adult', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.create_index(op.f('idx_movies_vote_count'), 'movies', ['vote_count'], unique=False)
    op.create_index(op.f('idx_movies_vote_average'), 'movies', ['vote_average'], unique=False)
    op.create_index(op.f('idx_movies_updated'), 'movies', ['updated_at'], unique=False)
    op.create_index(op.f('idx_movies_tone'), 'movies', ['tone'], unique=False)
    op.create_index(op.f('idx_movies_release_date'), 'movies', ['release_date'], unique=False)
    op.create_index(op.f('idx_movies_mood_tags'), 'movies', ['mood_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_movies_language'), 'movies', ['original_language'], unique=False)
    op.create_index(op.f('idx_movies_keywords'), 'movies', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_movies_genres'), 'movies', ['genres'], unique=False, postgresql_using='gin')
    op.alter_column('movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('movies', 'backdrop_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('movies', 'poster_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('movies', 'original_title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('movies', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('movies', 'created_at')
    op.drop_column('movies', 'spoken_languages')
    op.drop_column('movies', 'production_countries')
    op.drop_column('movies', 'status')
    op.drop_column('movies', 'tagline')
    op.create_unique_constraint(op.f('uq_list_interaction'), 'list_interactions', ['user_id', 'list_id', 'interaction_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_list_interactions_user'), 'list_interactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_list_interactions_type'), 'list_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('idx_list_interactions_list'), 'list_interactions', ['list_id'], unique=False)
    op.create_unique_constraint(op.f('uq_friendships_pair'), 'friendships', ['user_id', 'friend_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_friendships_user'), 'friendships', ['user_id'], unique=False)
    op.create_index(op.f('idx_friendships_status'), 'friendships', ['status'], unique=False)
    op.create_index(op.f('idx_friendships_friend'), 'friendships', ['friend_id'], unique=False)
    op.create_table('movie_vectors',
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id', name=op.f('movie_vectors_pkey'))
    )
    op.create_index(op.f('idx_movie_vectors_updated'), 'movie_vectors', ['updated_at'], unique=False)
    # ### end Alembic commands ###
